version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: installrequire
          command: npm i
      - run:
          name: test_myagent
          command: node myagent.js test
      - run:
          name: mkdir
          command: mkdir ~/myagent_binary;touch ~/myagent_binary/STOPPED_SUPPORT_FOR_x86
      - run:
          name: installpkg
          command: npm i pkg
      - run:
          name: buildbinary-linux
          command: node node_modules/pkg/lib-es5/bin.js -t node8-linux-x64 myagent.js;cp myagent ~/myagent_binary/myagent-linux;rm -rf myagent
      - run:
          name: test-for-linuxbinary
          command: chmod +x ~/myagent_binary/myagent-linux;~/myagent_binary/myagent-linux test
      - run:
          name: buildbinary-windows
          command: node node_modules/pkg/lib-es5/bin.js -t node8-win-x64 myagent.js;cp myagent.exe ~/myagent_binary/myagent-win.exe;rm -rf myagent.exe
      - run:
          name: buildbinary-macos
          command: node node_modules/pkg/lib-es5/bin.js -t node8-macos-x64 myagent.js;cp myagent ~/myagent_binary/myagent-macos;rm -rf myagent
      - store_artifacts:
          path: ~/myagent_binary

workflows:
  version: 2
  build:
    jobs:
      - build
