version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: installpkg
          command: npm i -g pkg
      - run:
          name: buildbinary
          command: 
            pkg -t linux myagent.js
            cp myagent ~/myagent
      - store_artifacts:
          path: ~/myagent

workflows:
  version: 2
  build:
    jobs:
      - build
