version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: test_myagent
          command: node myagent.js test
      - run:
          name: mkdir
          command: mkdir ~/myagent_binary
      - run:
          name: installrequire
          command: npm i
      - run:
          name: installpkg
          command: npm i pkg
      - run:
          name: buildbinary
          command: node node_modules/pkg/lib-es5/bin.js -t node8-linux myagent.js;cp myagent ~/myagent_binary/
      - store_artifacts:
          path: ~/myagent_binary

workflows:
  version: 2
  build:
    jobs:
      - build
