version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: installrequire
          command: npm i
      - run:
          name: test_myagent
          command: node myagent.js test
      - run:
          name: buildbinary
          command: make allplatform;mv build ~/myagent_binary
      - run:
          name: test-for-linuxbinary
          command: ~/myagent_binary/myagent-linux test
      - run:
          name: make-xz
          command: cd ~/myagent_binary;tar -cvf all.tar * ;xz -9 -e all.tar;xz -k -9 -e myagent-linux;xz -k -9 -e myagent-macos;xz -k -9 -e myagent-win64.exe
      - store_artifacts:
          path: ~/myagent_binary

workflows:
  version: 2
  build:
    jobs:
      - build
